version: '3.8'

services:
  postgres:
    restart: always
    ports:
      - 5554:5432
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file:
      - ./env/postgres.dev.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    restart: always
    ports:
      - "8000:80"
    build:
      context: .
      dockerfile: Dockerfile.pgadmin
    env_file:
      - ./env/pgadmin.dev.env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
